global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: prometheus2
    static_configs:
      - targets: ['prometheus2:9090']

  - job_name: mysqld-exporter2
    static_configs:
      - targets:
        - mysql2:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mysqld-exporter2:9104