version: '3.8'

services:

  prometheus:
    image: prom/prometheus:${PROMETHEUS_TAG}
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=1d'
    restart: always
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    container_name: grafana
    volumes:
      - grafana_vol:/var/lib/grafana
    restart: always
    ports:
      - 3000:3000

  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_TAG}
    container_name: node-exporter
    restart: always
    ports:
      - 9100:9100
      
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    ports:
      - 9093:9093

  mysql:
    # CREATE USER 'exp'@'%' IDENTIFIED BY '1234' WITH MAX_USER_CONNECTIONS 3;
    # GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exp'@'%';
    image: mysql:${MYSQL_TAG}
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=exp
      - MYSQL_PASSWORD=1234
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - '3306'

  mysqld-exporter:
    image: prom/mysqld-exporter:${MYSQL_EXPORTER_TAG}
    container_name: mysqld-exporter
    command:
      - '--config.my-cnf=/etc/.my.cnf'
    restart: always
    volumes:
      - ./mysqld-exporter/.my.cnf:/etc/.my.cnf
    depends_on:
      - mysql
    ports:
      - 9104:9104

  redis:
    image: redis:${REDIS_TAG}
    container_name: redis
    expose:
      - '6379'

  redis-exporter:
    image: oliver006/redis_exporter:${REDIS_EXPORTER_TAG}
    container_name: redis-exporter
    command: -redis.addr redis://redis:6379
    ports:
      - 9121:9121
    depends_on:
      - redis

  blackbox-exporter:
    image: prom/blackbox-exporter:${BLACKBOX_EXPORTER_TAG}
    container_name: blackbox-exporter
    volumes:
      - ./blackbox-exporter/blackbox.yml:/etc/blackbox/blackbox.yml
    command:
      - '--config.file=/etc/blackbox/blackbox.yml'
    ports:
      - 9115:9115

volumes:
  mysql_data:
  grafana_vol: