global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: alertmanager
    static_configs:
      - targets: ['alertmanager:9093']
  
  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']

  - job_name: mysqld-exporter
    static_configs:
      - targets:
        - mysql:3306
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mysqld-exporter:9104

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']